api_query_interval: 1.0
backend: triton
budget_tokens: 0
check_kernel: true
custom_prompt_key: None
dataset_name: ScalingIntelligence/KernelBench
dataset_src: local
hardware_gpu_name: None
include_hardware_info: false
is_reasoning_model: false
level: 2
log_prompt: false
max_tokens: 8192
model_name: gemini-3.8-flash
num_samples: 1
num_workers: 2
precision: fp32
prompt_option: one_shot
reasoning_effort: low
run_name: cloud_agents_l2
runs_dir: /Users/joeltaroreh/projects/challenges/KernelBench/runs
server_type: google
store_type: local
subset:
- 23
- 100
temperature: 0.0
verbose: false
